version: '3.8'

services:
  qp-assessment:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node app.js
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: "qp-assessment"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres_data:/Library/PostgreSql/16/data

volumes:
  postgres_data:
